### ISSUE TITLE
date first observation = `2005-2009` 

### ISSUE THREAD

**Issue by LienReyserhove** [trias-project/alien-mammals-checklist#2]
The date of first observation for `Muntiacus reevesi (Ogilby, 1839)` is `2005-2009`. I can't map this to `eventDate`. Should I keep `2005` or `2009`?

**Comment by sannegovaert** [comment]
@timadriaens @SanderDevisscher, can you look into this?

**Comment by timadriaens** [comment]
2004, the reference used for this is: D'hondt, B., Engels, P., Verbist, B., Vercammen, J., Huygens, W., Adriaens, T., & Casaer, J. (2023). Monitoring van een Vlaamse populatie van Chinese muntjak (Muntiacus reevesi) in het kader van bestrijding. Lutra (Leiden), 66(2), 105-121.
