### ISSUE TITLE
Pathway mapping

### ISSUE THREAD

**Issue by LienReyserhove** [trias-project/alien-mammals-checklist#4]
Pathway information should use the [vocabulary for pathway](https://rs.gbif.org/vocabulary/dwc/pathway_2022-02-02.xml).
Some I don't know, so a check should be good:

pathway | mapping | remarks
---|---|---
escape | ? | only for `Procyon cancrivorus (G.Cuvier, 1798)`
escape_fur_farm | fur |
unaided | unaided | 
escape_pet | pet | 
escape_farm | farmedAnimals? | to verify
escape_zoo | publicGardenZooAquaria | 
natural dispersal | naturalDispersal | 
release_hunting | hunting | 
stowaway_container/bulk | containerBulk |

**Comment by qgroom** [comment]
This is the document you need for details cbd.int/doc/c/9d85/3bc5/d640f059d03acd717602cd76/sbstta-22-inf-09-en.pdf

**Comment by sannegovaert** [comment]
@timadriaens, can you check this?

**Comment by timadriaens** [comment]
escape_farm = `farmedAnimals`
escape_pet = `pet` (and not just "escape from confinement")
the mapping looks good for the others
for Procyon cancrivorus the pathway is either `pet` or `publicGardenZooAquaria`
