### ISSUE TITLE
Change in species name induces change in `taxonID`

### ISSUE THREAD

**Issue by sannegovaert** [trias-project/alien-mammals-checklist#5]
The species name of Ovis orientalis Gmelin, 1774 is changed to Ovis gmelinii subsp. musimon (Pallas, 1811).
The unique taxonID's are based on scientific name and kingdom, so now the taxonID is also changed.
@timadriaens: is this a different species or just a different name for the same species?

@LienReyserhove How to deal with this?

**Comment by timadriaens** [comment]
It is a better name for what is actually meant

**Comment by timadriaens** [comment]
So we should change the taxon id imo

**Comment by sannegovaert** [comment]
We will use a new approach for taxonID, as explained here: https://github.com/trias-project/alien-herpetofauna-belgium/issues/24
